name: CD - Build and Push Docker Image

on:
    push:
      branches:
        - main
jobs:
    cd:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: "1.21.0"
  
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
        - name: Set version tag
          id: vars
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
  
        - name: Build Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/go-simple-cicd:${{ env.sha_short }} .
  
        - name: Push Docker image to Docker Hub
          run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/go-simple-cicd:${{ env.sha_short }}
  
